models:
  - name: "Model1"
    architecture:
      layers:
        - type: "Conv2D"
          filters: 32
          kernel_size: [3, 3]
          activation: "relu"
        - type: "MaxPooling2D"
          pool_size: [2, 2]
        - type: "Conv2D"
          filters: 64
          kernel_size: [3, 3]
          activation: "relu"
        - type: "MaxPooling2D"
          pool_size: [2, 2]
        - type: "Conv2D"
          filters: 64
          kernel_size: [3, 3]
          activation: "relu"
        - type: "MaxPooling2D"
          pool_size: [2, 2]
        - type: "Conv2D"
          filters: 64
          kernel_size: [3, 3]
          activation: "relu"
        - type: "MaxPooling2D"
          pool_size: [2, 2]
        - type: "Conv2D"
          filters: 64
          kernel_size: [3, 3]
          activation: "relu"
        - type: "MaxPooling2D"
          pool_size: [2, 2]
        - type: "Conv2D"
          filters: 64
          kernel_size: [3, 3]
          activation: "relu"
        - type: "MaxPooling2D"
          pool_size: [2, 2]
        - type: "Flatten"
        - type: "Dense"
          units: 64
          activation: "relu"
        - type: "Dropout"
          rate: 0.4
        - type: "Dense"
          units: 2
          activation: "sigmoid"

  - name: "Model2"
    architecture:
      layers:
        - type: "Conv2D"
          filters: 32
          kernel_size: [3, 3]
          activation: "relu"
        - type: "MaxPooling2D"
          pool_size: [2, 2]
        - type: "Conv2D"
          filters: 64
          kernel_size: [3, 3]
          activation: "relu"
        - type: "MaxPooling2D"
          pool_size: [2, 2]
        - type: "Conv2D"
          filters: 64
          kernel_size: [3, 3]
          activation: "relu"
        - type: "MaxPooling2D"
          pool_size: [2, 2]
        - type: "Conv2D"
          filters: 64
          kernel_size: [3, 3]
          activation: "relu"
        - type: "MaxPooling2D"
          pool_size: [2, 2]
        - type: "Conv2D"
          filters: 64
          kernel_size: [3, 3]
          activation: "relu"
        - type: "MaxPooling2D"
          pool_size: [2, 2]
        - type: "Conv2D"
          filters: 64
          kernel_size: [3, 3]
          activation: "relu"
        - type: "MaxPooling2D"
          pool_size: [2, 2]
        - type: "Flatten"
        - type: "Dense"
          units: 64
          activation: "relu"
        - type: "Dropout"
          rate: 0.3
        - type: "Dense"
          units: n_classes
          activation: "softmax"

